# Modelltraining und Experiment-Tracking

In diesem Notebook werden mehrere Modelle trainiert und mit MLflow dokumentiert.
Zusätzlich bleibt ein einfacher Basislauf mit Logistic Regression erhalten,
damit man zuerst ein Gefühl für den Datensatz bekommt, bevor die vollständige Modellsuche startet.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from loan_mlops.data import load_preprocessed_data
from loan_mlops.train import (
    register_best_model,
    results_to_frame,
    run_model_search,
    select_best_result,
    setup_mlflow_experiment,
    split_training_data,
)

c:\Users\bjoer\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import inspect
from loan_mlops.train import check_mlflow_connection

print(inspect.getsource(check_mlflow_connection))

def check_mlflow_connection(tracking_uri: str, timeout: int = 5) -> None:
    """
    Prüft, ob der MLflow-Server erreichbar ist.
    Dafür wird ein MLflow-API-Endpunkt angesprochen.
    Ein 400-Fehler ist hier akzeptabel, weil er zeigt, dass der Server antwortet.
    """
    check_url = tracking_uri.rstrip("/") + "/api/2.0/mlflow/experiments/search"

    try:
        response = requests.get(check_url, timeout=timeout)

        # 200 = sauber erreichbar
        # 400 = Server antwortet, Request ist nur inhaltlich nicht vollständig
        if response.status_code not in (200, 400):
            raise RuntimeError(
                f"MLflow antwortet unter '{check_url}', aber mit Status {response.status_code}."
            )

    except Exception as exc:
        raise RuntimeError(
            f"MLflow ist unter '{check_url}' nicht erreichbar. "
            "Prüfe, ob der MLflow-Service läuft."
        ) from exc

In [3]:
import requests
r = requests.get("http://localhost:5000/api/2.0/mlflow/experiments/search", timeout=5)
print(r.status_code)
print(r.text[:300])

400
{"error_code": "INVALID_PARAMETER_VALUE", "message": "Invalid value 0 for parameter 'max_results' supplied. It must be a positive integer"}

## 1. Vorverarbeiteten Datensatz laden

In [4]:
processed_data = load_preprocessed_data()
print(processed_data.shape)
processed_data.head()

(9578, 23)

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,...,dti_to_fico,int_rate_to_fico,revol_bal_to_inc,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business,not.fully.paid
0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,...,0.026431,0.000161,0.339459,0,1,0,0,0,0,0
1,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,...,0.020212,0.000151,0.517277,1,0,0,0,0,0,0
2,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,...,0.017053,0.000199,0.109719,0,1,0,0,0,0,0
3,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,...,0.011376,0.000142,0.396082,0,1,0,0,0,0,0
4,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,...,0.022444,0.000214,0.058663,1,0,0,0,0,0,0

## 2. Einfaches Basismodell

Bevor alle Kandidaten mit MLflow trainiert werden, wird einmal eine einfache Logistic Regression gebaut.
So sieht man schnell, ob der Datensatz grundsätzlich lernbar ist.

In [5]:
X_train, X_test, y_train, y_test = split_training_data(processed_data)

baseline_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)),
])

baseline_model.fit(X_train, y_train)

y_pred = baseline_model.predict(X_test)
y_prob = baseline_model.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.6388
ROC-AUC: 0.6804
Confusion Matrix:
[[1045  564]
 [ 128  179]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.65      0.75      1609
           1       0.24      0.58      0.34       307

    accuracy                           0.64      1916
   macro avg       0.57      0.62      0.55      1916
weighted avg       0.79      0.64      0.69      1916

In [6]:
import os
import socket
import requests

print("MLFLOW_TRACKING_URI ENV:", os.getenv("MLFLOW_TRACKING_URI"))

for url in ["http://localhost:5000", "http://mlflow:5000"]:
    try:
        r = requests.get(url, timeout=5)
        print(url, "->", r.status_code)
    except Exception as e:
        print(url, "-> FEHLER:", repr(e))

print("Hostname:", socket.gethostname())

MLFLOW_TRACKING_URI ENV: None
http://localhost:5000 -> 200
http://mlflow:5000 -> FEHLER: ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'mlflow\', port=5000): Max retries exceeded with url: / (Caused by NameResolutionError("HTTPConnection(host=\'mlflow\', port=5000): Failed to resolve \'mlflow\' ([Errno 11001] getaddrinfo failed)"))'))
Hostname: Björn

Die Basisauswertung ist noch nicht die endgültige Modellwahl.  
Sie dient vor allem dazu, die Richtung zu prüfen und einen ersten Vergleichspunkt zu haben.

## 3. MLflow-Experiment vorbereiten

In [7]:
import inspect
from loan_mlops.train import check_mlflow_connection, setup_mlflow_experiment

print(inspect.getsource(check_mlflow_connection))
print("-----")
print(inspect.getsource(setup_mlflow_experiment))

def check_mlflow_connection(tracking_uri: str, timeout: int = 5) -> None:
    """
    Prüft, ob der MLflow-Server erreichbar ist.
    Dafür wird ein MLflow-API-Endpunkt angesprochen.
    Ein 400-Fehler ist hier akzeptabel, weil er zeigt, dass der Server antwortet.
    """
    check_url = tracking_uri.rstrip("/") + "/api/2.0/mlflow/experiments/search"

    try:
        response = requests.get(check_url, timeout=timeout)

        # 200 = sauber erreichbar
        # 400 = Server antwortet, Request ist nur inhaltlich nicht vollständig
        if response.status_code not in (200, 400):
            raise RuntimeError(
                f"MLflow antwortet unter '{check_url}', aber mit Status {response.status_code}."
            )

    except Exception as exc:
        raise RuntimeError(
            f"MLflow ist unter '{check_url}' nicht erreichbar. "
            "Prüfe, ob der MLflow-Service läuft."
        ) from exc

-----
def setup_mlflow_experiment(
    experiment_name: str = DEFAULT_EXPERIMENT_NAME,
    tracking_uri: str = DEFAULT_TRACKING_URI,
) -> tuple[MlflowClient, Any]:
    if mlflow is None or MlflowClient is None:
        raise ModuleNotFoundError("mlflow ist nicht installiert.")

    check_mlflow_connection(tracking_uri)

    mlflow.set_tracking_uri(tracking_uri)
    client = MlflowClient(tracking_uri=tracking_uri)

    experiment = client.get_experiment_by_name(experiment_name)

    if experiment is not None and experiment.lifecycle_stage == "deleted":
        client.restore_experiment(experiment.experiment_id)

    mlflow.set_experiment(experiment_name)
    experiment = client.get_experiment_by_name(experiment_name)

    if experiment is None:
        raise RuntimeError(
            f"Experiment '{experiment_name}' konnte nicht erstellt oder geladen werden."
        )

    return client, experiment

In [8]:
client, experiment = setup_mlflow_experiment()
print("Tracking URI:", experiment.artifact_location)
print("Experiment ID:", experiment.experiment_id)

Tracking URI: /mlflow/artifacts/1
Experiment ID: 1

## 4. Mehrere Modelle trainieren

Jetzt werden drei Modellfamilien mit mehreren Parameterkombinationen getestet:

- Logistic Regression  
- Random Forest  
- Gradient Boosting

In [9]:
X_train, X_test, y_train, y_test = split_training_data(processed_data)
results = run_model_search(X_train, X_test, y_train, y_test)
len(results)

Trainiere LogisticRegression mit Parametern: {'C': 0.1, 'max_iter': 1000, 'class_weight': None, 'random_state': 42}

2026/03/13 14:13:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run LogisticRegression at: http://localhost:5000/#/experiments/1/runs/b72ac0ec15164852ab6a602634346429
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere LogisticRegression mit Parametern: {'C': 1.0, 'max_iter': 1000, 'class_weight': 'balanced', 'random_state': 42}

2026/03/13 14:13:09 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run LogisticRegression at: http://localhost:5000/#/experiments/1/runs/5d143b53531e45d0a90afe9595258590
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere LogisticRegression mit Parametern: {'C': 10.0, 'max_iter': 1000, 'class_weight': 'balanced', 'random_state': 42}

2026/03/13 14:13:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run LogisticRegression at: http://localhost:5000/#/experiments/1/runs/50806f4cab0c4f7a87a79aa0e79c2d7f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere RandomForest mit Parametern: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'random_state': 42}

2026/03/13 14:13:20 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RandomForest at: http://localhost:5000/#/experiments/1/runs/e341f443eb8a4329a384128fb9cd2949
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere RandomForest mit Parametern: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 5, 'random_state': 42}

2026/03/13 14:13:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RandomForest at: http://localhost:5000/#/experiments/1/runs/752c4d486d074547b596e88cf917bd76
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere RandomForest mit Parametern: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'random_state': 42}

2026/03/13 14:13:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RandomForest at: http://localhost:5000/#/experiments/1/runs/a1ae8f4914f243b39033bd02241bf1be
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere GradientBoosting mit Parametern: {'n_estimators': 100, 'learning_rate': 0.05, 'random_state': 42}

2026/03/13 14:13:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run GradientBoosting at: http://localhost:5000/#/experiments/1/runs/637929b6059c470481dbe1cd1b8d041e
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere GradientBoosting mit Parametern: {'n_estimators': 200, 'learning_rate': 0.05, 'random_state': 42}

2026/03/13 14:13:50 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run GradientBoosting at: http://localhost:5000/#/experiments/1/runs/9a5d98c8bbd2453f9613d9e5d3cea987
🧪 View experiment at: http://localhost:5000/#/experiments/1
Trainiere GradientBoosting mit Parametern: {'n_estimators': 100, 'learning_rate': 0.1, 'random_state': 42}

2026/03/13 14:13:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run GradientBoosting at: http://localhost:5000/#/experiments/1/runs/351c4144ce9f44ababa31b75d8052227
🧪 View experiment at: http://localhost:5000/#/experiments/1

9

In [14]:
results_df = results_to_frame(results).sort_values(
    by=["roc_auc", "f1_score"],
    ascending=False,
    na_position="last",
)
results_df

,model_type,run_id,C,max_iter,class_weight,random_state,accuracy,precision,recall,f1_score,roc_auc,n_estimators,max_depth,min_samples_split,learning_rate
1,LogisticRegression,5d143b53531e45d0a90afe9595258590,1.0,1000.0,balanced,42,0.638831,0.240915,0.583062,0.340952,0.680399,NaN,NaN,NaN,NaN
0,LogisticRegression,b72ac0ec15164852ab6a602634346429,0.1,1000.0,None,42,0.839770,0.500000,0.042345,0.078078,0.680314,NaN,NaN,NaN,NaN
2,LogisticRegression,50806f4cab0c4f7a87a79aa0e79c2d7f,10.0,1000.0,balanced,42,0.636743,0.240320,0.586319,0.340909,0.678626,NaN,NaN,NaN,NaN
3,RandomForest,e341f443eb8a4329a384128fb9cd2949,NaN,NaN,NaN,42,0.839248,0.400000,0.006515,0.012821,0.667388,100.0,10.0,2.0,NaN
4,RandomForest,752c4d486d074547b596e88cf917bd76,NaN,NaN,NaN,42,0.840292,0.555556,0.016287,0.031646,0.666309,200.0,15.0,5.0,NaN
7,GradientBoosting,9a5d98c8bbd2453f9613d9e5d3cea987,NaN,NaN,NaN,42,0.836117,0.294118,0.016287,0.030864,0.664744,200.0,NaN,NaN,0.05
6,GradientBoosting,637929b6059c470481dbe1cd1b8d041e,NaN,NaN,NaN,42,0.837161,0.222222,0.006515,0.012658,0.663542,100.0,NaN,NaN,0.05
8,GradientBoosting,351c4144ce9f44ababa31b75d8052227,NaN,NaN,NaN,42,0.834551,0.250000,0.016287,0.030581,0.661987,100.0,NaN,NaN,0.10
5,RandomForest,a1ae8f4914f243b39033bd02241bf1be,NaN,NaN,NaN,42,0.838205,0.333333,0.009772,0.018987,0.660910,300.0,NaN,10.0,NaN

## 5. Bestes Modell auswählen

Die Auswahl erfolgt zuerst über `roc_auc`.  
Falls für ein Modell keine Wahrscheinlichkeiten vorliegen sollten, wird auf den `f1_score` zurückgegriffen.

In [15]:
best_result = select_best_result(results)
best_result["model_type"], best_result["params"], best_result["metrics"]

('LogisticRegression',
 {'C': 1.0, 'max_iter': 1000, 'class_weight': 'balanced', 'random_state': 42},
 {'accuracy': 0.6388308977035491,
  'precision': 0.24091520861372812,
  'recall': 0.5830618892508144,
  'f1_score': 0.34095238095238095,
  'roc_auc': 0.6803991392067827})

## 6. Bestes Modell registrieren

Das beste Modell wird in der MLflow Model Registry registriert und direkt auf `Staging` gesetzt.

In [16]:
model_version, description = register_best_model(best_result, client=client)
print(f"Model 'loan_default_predictor' wurde als Version {model_version.version} registriert.")
print("\nBeschreibung der Modellversion:\n")
print(description)

Registered model 'loan_default_predictor' already exists. Creating a new version of this model...
2026/03/13 14:14:15 WARNING mlflow.tracking._model_registry.fluent: Run with id 5d143b53531e45d0a90afe9595258590 has no artifacts at artifact path 'model', registering model based on models:/m-85c5a6144fe24652ac23f375fbcb5e22 instead
2026/03/13 14:14:15 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: loan_default_predictor, version 3
Created version '3' of model 'loan_default_predictor'.
C:\Users\bjoer\Documents\Uni\loan-mlops\src\loan_mlops\train.py:301: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

Model 'loan_default_predictor' wurde als Version 3 registriert.

Beschreibung der Modellversion:

Loan Default Prediction Model v3

- Modelltyp: LogisticRegression
- Training durchgeführt am: 2026-03-13 14:14
- Beste Parameter: {'C': 1.0, 'max_iter': 1000, 'class_weight': 'balanced', 'random_state': 42}

Performance:
- Accuracy: 0.6388
- Precision: 0.2409
- Recall: 0.5831
- F1-Score: 0.3410
- ROC-AUC: 0.6804

## 7. Kurze Einordnung der Ergebnisse

Wichtig sind hier nicht nur Accuracy-Werte, sondern vor allem Precision, Recall, F1 und ROC-AUC.
Gerade bei unausgeglichenen Klassen reicht Accuracy allein nicht aus.

In [17]:
vergleich = results_df[[
    "model_type",
    "accuracy",
    "precision",
    "recall",
    "f1_score",
    "roc_auc",
]].sort_values("roc_auc", ascending=False, na_position="last")
vergleich

           model_type  accuracy  precision    recall  f1_score   roc_auc
1  LogisticRegression  0.638831   0.240915  0.583062  0.340952  0.680399
0  LogisticRegression  0.839770   0.500000  0.042345  0.078078  0.680314
2  LogisticRegression  0.636743   0.240320  0.586319  0.340909  0.678626
3        RandomForest  0.839248   0.400000  0.006515  0.012821  0.667388
4        RandomForest  0.840292   0.555556  0.016287  0.031646  0.666309
7    GradientBoosting  0.836117   0.294118  0.016287  0.030864  0.664744
6    GradientBoosting  0.837161   0.222222  0.006515  0.012658  0.663542
8    GradientBoosting  0.834551   0.250000  0.016287  0.030581  0.661987
5        RandomForest  0.838205   0.333333  0.009772  0.018987  0.660910